name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: sum_numbers
      id: sum_numbers
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 60
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SUM_NUMBERS_RESULTS: "${{steps.sum_numbers.outputs.result}}"
      with:
        runners: sum_numbers
